# Generated by Django 4.2.3 on 2023-07-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
