# Generated by Django 4.2.3 on 2023-07-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0002_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_url',
            field=models.ImageField(max_length=30, upload_to='uploads/images'),
        ),
    ]
