# Generated by Django 4.2.3 on 2023-07-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0003_alter_service_s_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=50)),
                ('s_url', models.ImageField(max_length=30, upload_to='uploads/images')),
                ('s_perce', models.PositiveIntegerField()),
            ],
        ),
    ]
