# Generated by Django 4.2.3 on 2023-07-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0004_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='s_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
