# Generated by Django 4.2.3 on 2023-07-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0005_alter_skill_s_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('entry_type', models.CharField(default='subscribe', max_length=10)),
            ],
        ),
    ]
