# Generated by Django 4.2.3 on 2023-02-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starter', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='entry_type',
            field=models.CharField(blank=True, default='subscribe', max_length=10, null=True),
        ),
    ]
